apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
  name: my-replica-sample
  namespace: mongodb
spec:
  members: 1
  version: 8.0.4-ent
  type: ReplicaSet
  security:
    authentication:
      enabled: true
      modes: ["SCRAM"]
    tls:
      ca: custom-ca # Ensure this ConfigMap contains the CA certificate
      enabled: true
  authentication:
    enabled: true
    modes: ["X509"]
    internalCluster: "X509"
  additionalMongodConfig:
    net:
      tls:
        mode: "requireTLS"
  opsManager:
    configMapRef:
      name: my-project
  credentials: my-credentials
  persistent: true
  podSpec:
    podTemplate:
      spec:
        containers:
          - name: mongodb-enterprise-database
            readinessProbe:
              exec:
                command:
                  - /opt/scripts/readinessprobe
              failureThreshold: 10
              initialDelaySeconds: 5
              periodSeconds: 5
              successThreshold: 1
              timeoutSeconds: 10
            resources:
              limits:
                cpu: "0.333"
                memory: "700Mi"
